import type { Store } from '../store/db.js';

/**
 * Directories that hold peripheral code: generated schema snapshots, demos, docs, tooling and
 * vendored/side modules. `demo`/`fixture` may sit anywhere in a segment ("watchOS Demo/",
 * "fixtures-app/"), the rest are whole segments. SQL/schema migrations are real, hand-written code
 * (not generated, not skipped) but they're numerous, mechanical, and rarely what a search or
 * subsystem label should lead with, so they're demoted the same way: `migrations/`, Rails'
 * `db/migrate/`, and a `*.migration.*` filename.
 *
 * `example(s)`/`sample(s)` are handled separately by {@link EXAMPLES_SEGMENT} below, because an
 * `example` segment is also the conventional Java/Kotlin reverse-domain package segment
 * (`com.example.*`, `org.example.*`) used by the default Android Studio / Gradle project
 * template — that is real application code, not a demo directory, and must not be demoted.
 */
export const PERIPHERAL_PATH =
  /(^|\/)(?:[^/]*(?:demos?|fixtures?)[^/]*|docs?|benchmarks?|bench|vendor|third_party|extras?|support|metrics|proto|website|www|migrations?)\/|(^|\/)db\/migrate\/|\.migration\.[^/]+$/i;

/** A path segment that is (or contains) `example(s)`/`sample(s)`, e.g. `examples`, `example-app`. */
const EXAMPLES_SEGMENT = /^[^/]*(?:examples?|samples?)[^/]*$/i;

/**
 * Reverse-domain segments conventionally used as the first component of a Java/Kotlin package
 * (`com.example`, `org.example`, `io.example`, ...). When an `example(s)` segment is immediately
 * preceded by one of these, it's a package name, not a demo directory.
 */
const REVERSE_DOMAIN_SEGMENT = /^(?:com|org|net|io|dev|app|me)$/i;

/**
 * A JVM source root (`src/<sourceSet>/java|kotlin|scala/`, e.g. `src/main/java/`,
 * `src/test/kotlin/`). An `example(s)` segment under one of these is a package segment, not a
 * demo directory, even without a preceding reverse-domain segment (e.g. `src/main/java/example/`).
 */
const JAVA_SRC_ROOT = /(^|\/)src\/[^/]+\/(?:java|kotlin|scala)\/$/i;

/**
 * Flutter/native platform-runner scaffolding generated by `flutter create` and almost never
 * hand-edited: `windows/runner`, `linux/runner`, `macos/Runner`, `ios/Runner`.
 */
const RUNNER_DIR = /(^|\/)[Rr]unner\//;

/**
 * Top-level Flutter/KMP platform directories. These are peripheral *only* when the repo root is
 * actually a Flutter or Gradle multi-platform project (see `hasFlutterOrKmpRoot`) — in a plain web
 * project `web/` or `android/` are ordinary source directories, not generated scaffolding.
 */
const PLATFORM_ROOT_DIR = /^(?:android|ios|macos|linux|windows|web)\//i;

/**
 * True when `path` (repo-relative) is peripheral: a migration snapshot, generated platform
 * scaffolding, a demo/example/vendor/docs directory, and so on. `flutterOrKmpRoot` should be the
 * result of `hasFlutterOrKmpRoot` (or an equivalent root check) — it gates the platform-directory
 * rule so a non-Flutter repo's `web/` or `android/` isn't wrongly demoted.
 */
export function isPeripheralPath(path: string, flutterOrKmpRoot = false): boolean {
  if (PERIPHERAL_PATH.test(path)) return true;
  if (isPeripheralExamplesSegment(path)) return true;
  if (RUNNER_DIR.test(path)) return true;
  if (flutterOrKmpRoot && PLATFORM_ROOT_DIR.test(path)) return true;
  return false;
}

/**
 * True when `path` has an `example(s)`/`sample(s)` directory segment that is *not* a Java-style
 * package segment (see {@link EXAMPLES_SEGMENT}'s doc comment above).
 */
function isPeripheralExamplesSegment(path: string): boolean {
  const segments = path.split('/');
  // The last segment is the filename, not a directory — only directory segments count.
  for (let i = 0; i < segments.length - 1; i++) {
    if (!EXAMPLES_SEGMENT.test(segments[i] ?? '')) continue;
    const prev = i > 0 ? (segments[i - 1] ?? '') : '';
    if (REVERSE_DOMAIN_SEGMENT.test(prev)) continue;
    if (JAVA_SRC_ROOT.test(segments.slice(0, i).join('/') + '/')) continue;
    return true;
  }
  return false;
}

/**
 * Does the repo root look like a Flutter or Kotlin-Multiplatform project? Checked via the
 * indexed `files` table (cheap: one indexed lookup) rather than the filesystem, so it works the
 * same whether called during indexing or from a query against an already-built store.
 */
export function hasFlutterOrKmpRoot(store: Store): boolean {
  const rows = store.prep("SELECT path FROM files WHERE path IN ('pubspec.yaml','settings.gradle','settings.gradle.kts')").all() as { path: string }[];
  return rows.length > 0;
}
