import { describe, it, expect, afterEach } from 'vitest';
import { symlinkSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { mkdtempSync, rmSync } from 'node:fs';
import { scanRepo, isGeneratedFilename, isGeneratedPath } from '../../src/index/scan.js';
import { indexRepo } from '../../src/index/indexer.js';
import { makeRepo, type TempRepo } from './helpers.js';

const repos: TempRepo[] = [];
const extra: string[] = [];
function repo(files: Record<string, string> = {}): TempRepo {
  const r = makeRepo(files);
  repos.push(r);
  return r;
}
afterEach(() => {
  while (repos.length) repos.pop()!.cleanup();
  while (extra.length) rmSync(extra.pop()!, { recursive: true, force: true });
});

const paths = (root: string) => scanRepo({ root }).map((f) => f.path).sort();

describe('scanRepo ignore handling', () => {
  it('matches a nested .gitignore against its own directory, not the repo root', () => {
    const r = repo({
      'foo/.gitignore': '/gen\nfoo/tmpout/\n',
      // `/gen` is anchored to foo/, so foo/gen is ignored and foo/sub/gen is not.
      'foo/gen/ignored.py': 'x = 1\n',
      'foo/sub/gen/kept.py': 'x = 1\n',
      // `foo/tmpout/` is relative to foo/, i.e. foo/foo/tmpout — not foo/tmpout.
      'foo/foo/tmpout/ignored2.py': 'x = 1\n',
      'foo/tmpout/kept2.py': 'x = 1\n',
      'foo/keep.py': 'x = 1\n',
      // A root-level `gen` is untouched by foo/.gitignore.
      'gen/root_kept.py': 'x = 1\n',
    });
    expect(paths(r.root)).toEqual(['foo/keep.py', 'foo/sub/gen/kept.py', 'foo/tmpout/kept2.py', 'gen/root_kept.py']);
  });

  it('still honours the root .gitignore for every depth', () => {
    const r = repo({ '.gitignore': '/gen\ntmpout/\n', 'gen/a.py': 'x = 1\n', 'deep/tmpout/b.py': 'x = 1\n', 'deep/keep.py': 'x = 1\n', 'sub/gen/c.py': 'x = 1\n' });
    expect(paths(r.root)).toEqual(['deep/keep.py', 'sub/gen/c.py']);
  });
});

describe('scanRepo symlinks', () => {
  it('follows file symlinks that resolve inside the repository and skips the rest', () => {
    const r = repo({ 'real/a.py': 'def a():\n    return 1\n', 'keep.py': 'x = 1\n' });
    symlinkSync(join(r.root, 'real', 'a.py'), join(r.root, 'link_inside.py'));

    const outsideBase = mkdtempSync(join(tmpdir(), 'symbra-outside-'));
    extra.push(outsideBase);
    writeFileSync(join(outsideBase, 'b.py'), 'def b():\n    return 2\n');
    symlinkSync(join(outsideBase, 'b.py'), join(r.root, 'link_outside.py'));
    symlinkSync(join(r.root, 'nowhere.py'), join(r.root, 'link_broken.py'));
    // A directory symlink would let the walk cycle, so it stays skipped.
    mkdirSync(join(r.root, 'realdir'), { recursive: true });
    writeFileSync(join(r.root, 'realdir', 'c.py'), 'x = 1\n');
    symlinkSync(join(r.root, 'realdir'), join(r.root, 'linkdir'));

    expect(paths(r.root)).toEqual(['keep.py', 'link_inside.py', 'real/a.py', 'realdir/c.py']);
  });

  it('reports how many symlinks it skipped', () => {
    const r = repo({ 'keep.py': 'x = 1\n' });
    symlinkSync(join(r.root, 'nowhere.py'), join(r.root, 'broken.py'));
    const msgs: string[] = [];
    scanRepo({ root: r.root, log: (m) => msgs.push(m) });
    expect(msgs.join('\n')).toMatch(/skipped 1 symlink/);
  });
});

describe('isGeneratedFilename', () => {
  it('flags hashed bundle output and known chunk names', () => {
    expect(isGeneratedFilename('index-DrLLgu_7.js')).toBe(true);
    expect(isGeneratedFilename('main.a1b2c3d4.js')).toBe(true);
    expect(isGeneratedFilename('chunk-XYZ.js')).toBe(true);
    expect(isGeneratedFilename('vendor.js')).toBe(true);
    expect(isGeneratedFilename('app.min.js')).toBe(true);
    expect(isGeneratedFilename('app.bundle.js')).toBe(true);
  });

  it('leaves ordinary hyphenated/dotted source names alone', () => {
    expect(isGeneratedFilename('use-router.js')).toBe(false);
    expect(isGeneratedFilename('app.config.js')).toBe(false);
    expect(isGeneratedFilename('index.js')).toBe(false);
    expect(isGeneratedFilename('date-utils.js')).toBe(false);
  });
});

describe('generated/minified file detection end to end', () => {
  it('excludes a hashed bundle at scan time; skips a minified file and an @generated file at index time', async () => {
    const r = repo({
      'assets/index-DrLLgu_7.js': 'x'.repeat(10),
      // a plain-named build artifact: one huge line, well past the minified-content threshold
      'src/bigfile.js': `var x=1;${'a'.repeat(6000)};`,
      'src/legacy.ts': '// @generated by codegen\nexport const value = 1;\n',
      'src/normal.ts': 'export function normal() {\n  return 1;\n}\n',
    });

    // scan.ts filters the hashed bundle by name; the minified file and the @generated file are
    // plain-named and only get caught later, by indexer.ts's content check.
    expect(paths(r.root)).toEqual(['src/bigfile.js', 'src/legacy.ts', 'src/normal.ts']);

    const stats = await indexRepo({ root: r.root, dbPath: r.dbPath, embed: false });
    expect(stats.skippedGenerated).toBe(3);
    expect(stats.files).toBe(3);
  });

  it('skips a Serverpod-style "DO NOT MODIFY" header and a .g.dart file, keeps hand-written code', async () => {
    const r = repo({
      // Serverpod / protoc-style banner: not `@generated`, not `do not edit` — the literal phrase
      // codegen tools like Serverpod actually stamp.
      'lib/src/generated/protocol.dart': '/* AUTOMATICALLY GENERATED CODE DO NOT MODIFY */\nclass Protocol {}\n',
      'lib/src/model.g.dart': 'part of model;\nProject _$ProjectFromJson(Map json) => Project();\n',
      'lib/src/model.dart': 'class Project {\n  String name = "";\n}\n',
    });
    const stats = await indexRepo({ root: r.root, dbPath: r.dbPath, embed: false });
    // protocol.dart is also caught by the generated/ directory heuristic in scan.ts, so both it
    // and model.g.dart never reach indexer.ts's content check.
    expect(paths(r.root)).toEqual(['lib/src/model.dart']);
    expect(stats.skippedGenerated).toBe(2);
  });

  it('excludes a `generated/` directory but not an ordinary `gen/` one', () => {
    expect(isGeneratedPath('lib/src/generated/protocol.dart')).toBe(true);
    expect(isGeneratedPath('proto/__generated__/foo.py')).toBe(true);
    expect(isGeneratedPath('src/gen/handwritten.ts')).toBe(false);

    const r = repo({
      'lib/src/generated/protocol.dart': 'class Protocol {}\n',
      'src/gen/handwritten.ts': 'export function real() { return 1; }\n',
    });
    expect(paths(r.root)).toEqual(['src/gen/handwritten.ts']);
  });

  it('a `.symbraignore` negation forces a content-marker-skipped file back in', async () => {
    const r = repo({
      '.symbraignore': '!src/keep_me.ts\n',
      'src/keep_me.ts': '// AUTOMATICALLY GENERATED - DO NOT MODIFY\nexport const kept = 1;\n',
      'src/drop_me.ts': '// AUTOMATICALLY GENERATED - DO NOT MODIFY\nexport const dropped = 1;\n',
    });
    const stats = await indexRepo({ root: r.root, dbPath: r.dbPath, embed: false });
    expect(stats.skippedGenerated).toBe(1);
    expect(stats.files).toBe(2);
  });

  it('keeps a migration file indexed (real code, just demoted in ranking)', async () => {
    const r = repo({
      'migrations/20240101_add_users.sql': 'CREATE TABLE users (id INTEGER PRIMARY KEY);\n',
      'src/app.ts': 'export function app() { return 1; }\n',
    });
    expect(paths(r.root)).toEqual(['migrations/20240101_add_users.sql', 'src/app.ts']);
    const stats = await indexRepo({ root: r.root, dbPath: r.dbPath, embed: false });
    expect(stats.skippedGenerated).toBe(0);
    expect(stats.files).toBe(2);

    const { PERIPHERAL_PATH } = await import('../../src/query/search.js');
    expect(PERIPHERAL_PATH.test('migrations/20240101_add_users.sql')).toBe(true);
    expect(PERIPHERAL_PATH.test('src/app.ts')).toBe(false);
  });
});
